[🐳] Use dockerindocker for CI

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,5 +1,4 @@
 variables:
-  REGISTRY_AUTH_FILE: auth.json
   IMAGE_NAME: koleg-client
 
 stages:
@@ -8,40 +7,75 @@ stages:
   - deploy
 
 .docker_login:
-  image: jbenden/buildah
+  image: docker:stable
+  services:
+    - docker:dind
   before_script:
-   - |
-    echo "$SCW_REGISTRY_TOKEN" \
-     | buildah login -u "$SCW_REGISTRY_USER" --password-stdin $SCW_REGISTRY
+    - >
+      echo "$SCW_REGISTRY_TOKEN"
+      | docker login
+      --username $SCW_REGISTRY_USER
+      $SCW_REGISTRY
+      --password-stdin
 
 🔥build_prod:
   stage: 🏗build
   extends: .docker_login
   script: |
-    buildah bud \
-      --storage-driver "vfs" \
+    docker pull \
+      $SCW_REGISTRY/$IMAGE_NAME:latest || true
+    docker build \
+      -t $SCW_REGISTRY/$IMAGE_NAME:latest \
+      -t $SCW_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA \
+      --cache-from $SCW_REGISTRY:latest \
       --build-arg='PROD=false' \
-      -t $IMAGE_NAME .
+      .
     echo "Push image to registry"
-    buildah push \
-      $IMAGE_NAME \
-      docker://$SCW_REGISTRY/$IMAGE_NAME:latest
-    buildah push \
-      $IMAGE_NAME \
-      docker://SCW_REGISTRY/$IMAGE_NAME:${CI_COMMIT_SHA}
+    docker push \
+      $SCW_REGISTRY/$IMAGE_NAME:latest
+    docker push \
+      $SCW_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA
 
 🚑build_debug:
   stage: 🏗build
   extends: .docker_login
   script: |
-    buildah bud \
-      --storage-driver "vfs" \
-      --build-arg='PROD=false' \
-      -t $IMAGE_NAME .
+    docker pull \
+      $SCW_REGISTRY/$IMAGE_NAME:debug || true
+    docker build \
+      -t $SCW_REGISTRY/$IMAGE_NAME:debug \
+      -t $SCW_REGISTRY/$IMAGE_NAME:debug-$CI_COMMIT_SHA \
+      --cache-from $SCW_REGISTRY:debug \
+      --build-arg='PROD=true' \
+      .
     echo "Push image to registry"
-    buildah push \
-      $IMAGE_NAME \
-      docker://$SCW_REGISTRY/$IMAGE_NAME:debug
-    buildah push \
-      $IMAGE_NAME \
-      docker://$SCW_REGISTRY/$IMAGE_NAME:debug-${CI_COMMIT_SHA}
+    docker push \
+      $SCW_REGISTRY/$IMAGE_NAME:debug
+    docker push \
+      $SCW_REGISTRY/$IMAGE_NAME:debug-$CI_COMMIT_SHA
+
+☸️production_deploy:
+  stage: deploy
+  image:
+    name: bitnami/kubectl:latest
+    entrypoint: ["/bin/bash", "-c"]
+  script: |
+    - >
+      /opt/bitnami/kubectl/bin/kubectl
+      set image deployment.v1.apps/$IMAGE_NAME
+      $IMAGE_NAME=$SCW_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA
+      --namespace production
+      --kubeconfig $SCW_KUBECONFIG
+      --record
+    - >
+      /opt/bitnami/kubectl/bin/kubectl
+      rollout status deployment.v1.apps/$IMAGE_NAME
+      --timeout=5m
+      --namespace production
+      --kubeconfig $SCW_KUBECONFIG
+      || ( kubectl
+      --namespace production
+      --kubeconfig $SCW_KUBECONFIG
+      rollout undo deployment.v1.apps/$IMAGE_NAME
+      && echo "❌ deployment failed, return to previous deployment"
+      && exit 1 )
