[#21][🐳] Reanable docker container and clean up repo

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,10 +1,9 @@
-variables:
-  IMAGE_NAME: koleg-client
-
 stages:
+  - 📜tests
   - 🐳login
   - 🏗build
-  - deploy
+  - 🔒security
+  - 🚀deploy
 
 .docker_login:
   image: docker:stable
@@ -18,6 +17,19 @@ stages:
       $SCW_REGISTRY
       --password-stdin
 
+🛏️tests_coverage:
+  stage: 📜tests
+  image: node:14.2.0
+  script: |
+    yarn
+    yarn coverage
+
+🐳dockerfile_lint:
+  stage: 📜tests
+  image: hadolint/hadolint
+  script: |
+    hadolint -c .hadolint.yaml Dockerfile
+
 🔥build_prod:
   stage: 🏗build
   extends: .docker_login
@@ -27,8 +39,7 @@ stages:
     docker build \
       -t $SCW_REGISTRY/$IMAGE_NAME:latest \
       -t $SCW_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA \
-      --cache-from $SCW_REGISTRY:latest \
-      --build-arg='PROD=false' \
+      --cache-from $SCW_REGISTRY/$IMAGE_NAME:latest \
       .
     echo "Push image to registry"
     docker push \
@@ -36,46 +47,28 @@ stages:
     docker push \
       $SCW_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA
 
-🚑build_debug:
-  stage: 🏗build
-  extends: .docker_login
-  script: |
-    docker pull \
-      $SCW_REGISTRY/$IMAGE_NAME:debug || true
-    docker build \
-      -t $SCW_REGISTRY/$IMAGE_NAME:debug \
-      -t $SCW_REGISTRY/$IMAGE_NAME:debug-$CI_COMMIT_SHA \
-      --cache-from $SCW_REGISTRY:debug \
-      --build-arg='PROD=true' \
-      .
-    echo "Push image to registry"
-    docker push \
-      $SCW_REGISTRY/$IMAGE_NAME:debug
-    docker push \
-      $SCW_REGISTRY/$IMAGE_NAME:debug-$CI_COMMIT_SHA
-
 ☸️production_deploy:
-  stage: deploy
-  image:
-    name: bitnami/kubectl:latest
-    entrypoint: ["/bin/bash", "-c"]
+  stage: 🚀deploy
+  image: google/cloud-sdk
+  only:
+    - master
+    - develop
   script: |
-    - >
-      /opt/bitnami/kubectl/bin/kubectl
-      set image deployment.v1.apps/$IMAGE_NAME
-      $IMAGE_NAME=$SCW_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA
-      --namespace production
-      --kubeconfig $SCW_KUBECONFIG
+    echo "Deploy on branch: ${CI_COMMIT_BRANCH}"
+    kubectl \
+      set image deployment/$IMAGE_NAME \
+      ${IMAGE_NAME}=${SCW_REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_SHA} \
+      --namespace "${CI_COMMIT_BRANCH}" \
+      --kubeconfig "$SCW_KUBECONFIG" \
       --record
-    - >
-      /opt/bitnami/kubectl/bin/kubectl
-      rollout status deployment.v1.apps/$IMAGE_NAME
-      --timeout=5m
-      --namespace production
-      --kubeconfig $SCW_KUBECONFIG
-      || ( kubectl
-      --namespace production
-      --kubeconfig $SCW_KUBECONFIG
-      rollout undo deployment.v1.apps/$IMAGE_NAME
-      && echo "❌ deployment failed, return to previous deployment"
-      && exit 1 )
+    kubectl \
+      rollout status deployment/$IMAGE_NAME \
+      --timeout=5m \
+      --namespace "${CI_COMMIT_BRANCH}" \
+      --kubeconfig $SCW_KUBECONFIG \
+    || ( kubectl \
+        --namespace "${CI_COMMIT_BRANCH}" \
+        --kubeconfig $SCW_KUBECONFIG \
+        rollout undo deployment/$IMAGE_NAME \
+        && echo "❌ deployment failed, return to previous deployment" \
+        && exit 1 )
